inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'vendor/**/*'
    - 'bin/**'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
Layout/LineLength:
  Max: 120
Layout/AccessModifierIndentation:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Enabled: false
Metrics/ModuleLength:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Max: 11
RSpec/NestedGroups:
  Enabled: false
Rails/SaveBang:
  Enabled: false
RSpec/FilePath:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  MinBodyLength: 2
Style/StringLiterals:
  EnforcedStyle: single_quotes

