name: 'Build and push the Docker image'
description: 'Builds the Docker image and pushes it to the ECR repository.'

inputs:
  ecr-url:
    required: true
  ref:
    required: true
  application-secret-id:
    required: true
  region:
    required: false
    default: 'eu-west-2'
runs:
  using: 'composite'
  steps:
    - run: |
        aws secretsmanager \
          get-secret-value \
          --secret-id "${{ inputs.application-secret-id }}" \
          --region 'eu-west-2' \
          --query 'SecretString' \
          --output text | jq -r 'to_entries | map("\(.key)=\(.value)") | join("\n")' > .env.production

        aws ecr get-login-password --region ${{ inputs.region }} \
          | docker login --username AWS --password-stdin "${{ inputs.ecr-url }}"

        echo ${{ inputs.ref }} >REVISION

        docker build -t "${{ inputs.ecr-url }}:${{ inputs.ref }}" .
        docker push "${{ inputs.ecr-url }}:${{ inputs.ref }}"
      shell: bash
