name: Deploy to staging

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to deploy'
        required: true
        default: 'main'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  ECR_URL: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-duty-calculator-production
  ENVIRONMENT: staging
  IAM_ROLE_ARN: arn:aws:iam::451934005581:role/CircleCi_Terraform-Role
  SECRET_ID: duty-calculator-configuration
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ env.ENVIRONMENT }}
          ref: ${{ inputs.ref || steps.docker-tag.outputs.DOCKER_TAG }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: ./.github/actions/build-and-push
        with:
          application-secret-id: ${{ env.SECRET_ID }}
          ecr-url: ${{ env.ECR_URL }}
          ref: ${{ steps.docker-tag.outputs.DOCKER_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4.1.0
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/terraform-apply
        with:
          environment: ${{ env.ENVIRONMENT }}
          ref: ${{ inputs.ref || steps.docker-tag.outputs.DOCKER_TAG }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

  post-deploy:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    needs: deploy
    with:
      test-url: "https://staging.trade-tariff.service.gov.uk"
      ref: main

  notifications:
      runs-on: ubuntu-latest
      needs: post-deploy
      if: always()
      steps:
        - uses: actions/checkout@v4.1.0
        - uses: ./.github/actions/slack-notify
          with:
            result: ${{ needs.post-deploy.result }}
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
