name: Deploy to development

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'The git ref to deploy'
        required: true
        default: 'main'

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  ECR_URL: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-duty-calculator-production
  ENVIRONMENT: development
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-ECS-Deployments-Role
  SECRET_ID: duty-calculator-configuration
  SKIP: terraform_docs,actionlint-docker
  TF_INPUT: 0
  TF_IN_AUTOMATION: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - id: ruby-version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> "$GITHUB_OUTPUT"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
          bundler-cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8
      - uses: ./.github/actions/setup-tflint
      - uses: ./.github/actions/setup-ssh
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: cd terraform/ && terraform init -backend=false -reconfigure
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: bundle exec rake lint:scss
      - run: bundle exec brakeman

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: ruby-version
        run: echo "RUBY_VERSION=$(cat .ruby-version)" >> "$GITHUB_OUTPUT"
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.RUBY_VERSION }}
          bundler-cache: true
      - uses: actions/setup-node@v4
        with:
          cache: yarn
      - run: yarn install --frozen-lockfile
      - run: bundle exec rspec

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/terraform-plan
        with:
          environment: ${{ env.ENVIRONMENT }}
          ref: ${{ inputs.ref || steps.docker-tag.outputs.DOCKER_TAG }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - uses: ./.github/actions/build-and-push
        with:
          application-secret-id: ${{ env.SECRET_ID }}
          ecr-url: ${{ env.ECR_URL }}
          ref: ${{ steps.docker-tag.outputs.DOCKER_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
      - test
    steps:
      - uses: actions/checkout@v4.1.0
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - uses: ./.github/actions/terraform-apply
        with:
          environment: ${{ env.ENVIRONMENT }}
          ref: ${{ inputs.ref || steps.docker-tag.outputs.DOCKER_TAG }}
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

  post-deploy:
    uses: trade-tariff/trade-tariff-tools/.github/workflows/e2e-tests.yml@main
    needs: deploy
    with:
      test-url: "https://dev.trade-tariff.service.gov.uk"
      ref: main

  notifications:
      runs-on: ubuntu-latest
      needs: post-deploy
      if: always()
      steps:
        - uses: actions/checkout@v4.1.0
        - uses: ./.github/actions/slack-notify
          with:
            result: ${{ needs.post-deploy.result }}
            slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
